theme: jekyll-theme-cayman
title: Welcome to Yong Lai's Studio!
description: Please feel free to look around my workshop!
collections:
    authors:
        output: true

defaults:
    - scope:
        path: ""
        type: "author"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"
